// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkemjvxfpztjhjeclesy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZW1qdnhmcHp0amhqZWNsZXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDA2NzEsImV4cCI6MjA2ODc3NjY3MX0.MpF-TchwX-QylPMX0qSKGy66JYETCCab6hvNyouWr_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});